name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1
      - name: Run tests
        run: |
          lua test.lua